#image: Visual Studio 2015

#install:
#- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

install:
  - ps: (New-Object System.Net.WebClient).DownloadFile('https://go.microsoft.com/fwlink/?LinkID=824659&clcid=0x409','SSDTSetup.exe');Start-Process 'SSDTSetup.exe /q /norestart /passive'

#before_build:
#  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
#  - ps: Vsix-TokenReplacement TeamCoding\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'


build_script:
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

#after_test:
#  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))